# Generated by Django 5.1 on 2024-08-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authorid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
