# Generated by Django 5.1 on 2024-08-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_authorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
